[project]
name = "aws-setup"
version = "0.1.0"
description = "Project to set up AWS for DE"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "boto3>=1.36.16",
    "botocore>=1.36.16",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.9.5",
]
